apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-nginx-config
data:
  filebeat.yml: |-
    logging:
      level: info
      json: true
      metrics:
        enabled: false

    tags:
      - "nginx-access"
    
    filebeat.modules:
    - module: nginx
      error:
        enabled: true   
        var.paths: ["/var/log/nginx/error.log"]
      ingress_controller: 
        enabled: true
        var.paths: ["/var/log/nginx/access.log"]

    processors:
      - add_id: ~
      - add_kubernetes_metadata:
          namespace: ingress-nginx
          in_cluster: true     
          default_indexers.enabled: false
          default_matchers.enabled: false
          indexers:
            - pod_name:
          matchers:
            - field_format:
                format: '${POD_NAMESPACE}/${POD_NAME}'
                         
    output.kafka:
      enabled: false
      hosts: ["kafka-svc.logging:9092"]
      topic: 'containers'
      partition.hash:
        reachable_only: true
      required_acks: 1
      max_message_bytes: 15728640
      client_id: "${POD_NAME}"

    output.console:
      enabled: false
      pretty: true

    output.logstash:
      enabled: true
      hosts: ["elk-logstash-indexer.logging:5044"]  